# Use the official Node.js 20 image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Expose the port on which the NestJS application will run
EXPOSE 1209

# Start the NestJS application
CMD ["npm", "run", "start:dev"]
